---
- name: Get the items in the Dock.
  ansible.builtin.command:
    cmd: dockutil --list 
  register: dock_items
  changed_when: false
  failed_when: >
    "No such file or directory" in dock_items.stdout
    or "command not found" in dock_items.stdout
  tags: ['dock']

- name: Generate a list of items from whats in the dock.
  set_fact:
    dock_items_list: "{{ dock_items_list + [(item | replace('\t', ' ') | regex_search('([^ ]+)$'))] }}"
  with_items: "{{ dock_items.stdout_lines }}"
  vars:
    dock_items_list: []

- name: Remove the items in the Dock.
  ansible.builtin.include_tasks: dock-remove.yml
  loop: "{{ dock_items_list | default([]) }}"
  loop_control:
    extended: true
    extended_allitems: false
  tags: ['dock']