---
- name: Install dockutil.
  community.general.homebrew:
    name: dockutil
    state: present
  notify:
    - Clear homebrew cache
  when: dockutil_install
  tags: ['dock']

- name: Clear Dock items.
  ansible.builtin.include_tasks: dock-clear.yml
  when: dockutil_clear
  tags: ['dock']
